on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '6'
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test